import Foundation

/// The car's own alerts, and what we want to happen when they fire.
///
/// This is a different thing from an `AlertRule`. A rule is *observational*:
/// we watch a number and decide whether it's worth mentioning. A chime is
/// *interventional*: the car already has an opinion and is acting on it, and
/// the only question is what happens to a sound that's going to play whether
/// we like it or not.
///
/// Hence a policy per chime rather than a rule per signal.
public struct Chime: Sendable, Identifiable, Hashable {
    public enum Reach: Sendable, Hashable {
        /// Generated by the combination meter — needs the speaker tap.
        case clusterTap
        /// Adjustable through dealer/SSM settings, or UDS writes to the body unit.
        case bodySetting
        /// Routed through the head unit, which has its own volume control.
        case headUnit

        public var describedReach: String {
            switch self {
            case .clusterTap: return "needs cluster speaker tap"
            case .bodySetting: return "dealer setting or UDS write"
            case .headUnit: return "head-unit volume setting"
            }
        }
    }

    public let id: String
    public let name: String
    public let detail: String
    public let reach: Reach
    /// The CAN signal that triggers it, when we can see one. Lets the
    /// interception board know *which* chime is playing.
    public let signal: ProprietarySignalRef?

    public init(id: String, name: String, detail: String, reach: Reach,
                signal: ProprietarySignalRef? = nil) {
        self.id = id
        self.name = name
        self.detail = detail
        self.reach = reach
        self.signal = signal
    }
}

/// Avoids Sterope depending on Maia's concrete signal type here.
public struct ProprietarySignalRef: Sendable, Hashable {
    public let id: UInt16
    public init(id: UInt16) { self.id = id }
}

/// What we do when a chime fires.
public enum ChimeAction: String, Sendable, Codable, CaseIterable {
    /// Leave the car alone. The honest default until hardware exists.
    case passthrough
    /// Attenuate the factory tone.
    case quieter
    /// Suppress it entirely.
    case muted
    /// Suppress it and play our own sound instead.
    case replaced

    public var displayName: String {
        switch self {
        case .passthrough: return "Pass through"
        case .quieter: return "Quieter"
        case .muted: return "Muted"
        case .replaced: return "Replace"
        }
    }
}

public struct ChimePolicy: Sendable, Codable, Equatable, Identifiable {
    public var id: String          // matches Chime.id
    public var action: ChimeAction
    /// Used when action == .replaced.
    public var sound: AlertSound
    public var volume: Double

    public init(id: String, action: ChimeAction = .passthrough,
                sound: AlertSound = .silent, volume: Double = 1.0) {
        self.id = id
        self.action = action
        self.sound = sound
        self.volume = volume
    }
}

public extension Chime {
    /// The 2022 Forester's chimes, from docs/design/chimes.md.
    static let foresterChimes: [Chime] = [
        Chime(id: "gate", name: "Rear gate ajar",
              detail: "The one that started this project. Fires continuously while driving with the gate open.",
              reach: .clusterTap, signal: ProprietarySignalRef(id: 0x100)),
        Chime(id: "seatbelt", name: "Seatbelt reminder",
              detail: "Escalates with speed and time. No factory setting exists for it.",
              reach: .clusterTap, signal: ProprietarySignalRef(id: 0x110)),
        Chime(id: "door", name: "Door ajar",
              detail: "Door open with the ignition on.",
              reach: .clusterTap, signal: ProprietarySignalRef(id: 0x101)),
        Chime(id: "turnsignal", name: "Turn signal tick",
              detail: "Synthesized by the cluster, not a physical relay.",
              reach: .clusterTap),
        Chime(id: "eyesight", name: "EyeSight / pre-collision",
              detail: "Routed through the head unit and the cluster on the 2022.",
              reach: .headUnit),
        Chime(id: "reverse", name: "Reverse / park sensors",
              detail: "Body unit through the rear speaker.",
              reach: .headUnit),
        Chime(id: "keyless", name: "Keyless entry beep",
              detail: "Separate buzzer. Seven volume levels including off, via dealer settings.",
              reach: .bodySetting),
    ]
}

/// JSON-file-backed chime policies, one per chime.
public actor ChimePolicyStore {
    private let fileURL: URL
    private var policies: [String: ChimePolicy]

    public init(directory: URL? = nil) {
        let base = directory ?? FileManager.default
            .urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
            .appendingPathComponent("pleiades", isDirectory: true)
        try? FileManager.default.createDirectory(at: base, withIntermediateDirectories: true)
        fileURL = base.appendingPathComponent("chime-policies.json")
        if let data = try? Data(contentsOf: fileURL),
           let loaded = try? JSONDecoder().decode([String: ChimePolicy].self, from: data) {
            policies = loaded
        } else {
            policies = [:]
        }
    }

    /// Every chime, with its stored policy or a passthrough default.
    public func all() -> [ChimePolicy] {
        Chime.foresterChimes.map { policies[$0.id] ?? ChimePolicy(id: $0.id) }
    }

    public func policy(for id: String) -> ChimePolicy {
        policies[id] ?? ChimePolicy(id: id)
    }

    public func save(_ policy: ChimePolicy) {
        policies[policy.id] = policy
        persist()
    }

    public func resetAll() {
        policies = [:]
        persist()
    }

    private func persist() {
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        try? encoder.encode(policies).write(to: fileURL, options: .atomic)
    }
}
