import Foundation
import Maia

/// The car's own alerts, and what we want to happen when they fire.
///
/// This is a different thing from an `AlertRule`. A rule is *observational*:
/// we watch a number and decide whether it's worth mentioning. A chime is
/// *interventional*: the car already has an opinion and is acting on it, and
/// the only question is what happens to a sound that's going to play whether
/// we like it or not.
///
/// Hence a policy per chime rather than a rule per signal.
public struct Chime: Sendable, Identifiable, Hashable {
    public enum Reach: Sendable, Hashable {
        /// Generated by the combination meter — needs the speaker tap.
        case clusterTap
        /// Adjustable through dealer/SSM settings, or UDS writes to the body unit.
        case bodySetting
        /// Routed through the head unit, which has its own volume control.
        case headUnit

        public var describedReach: String {
            switch self {
            case .clusterTap: return "needs cluster speaker tap"
            case .bodySetting: return "dealer setting or UDS write"
            case .headUnit: return "head-unit volume setting"
            }
        }
    }

    public let id: String
    public let name: String
    public let detail: String
    public let reach: Reach
    /// Where this particular chime can be intercepted. Not every chime has
    /// an input we can reach — a turn-signal tick is synthesized entirely
    /// inside the cluster from a stalk switch we may not tap.
    public let points: Set<InterceptionPoint>
    /// The CAN signal that triggers it, when we can see one. Lets the
    /// interception board know *which* chime is playing.
    public let signal: ProprietarySignalRef?

    public init(id: String, name: String, detail: String, reach: Reach,
                points: Set<InterceptionPoint> = [.output],
                signal: ProprietarySignalRef? = nil) {
        self.id = id
        self.name = name
        self.detail = detail
        self.reach = reach
        self.points = points
        self.signal = signal
    }

    /// Actions this chime could support, given hardware.
    public func availableActions() -> [ChimeAction] {
        ChimeAction.allCases.filter { action in
            action == .passthrough || !action.requiredPoints.isDisjoint(with: points)
        }
    }
}

/// Avoids Sterope depending on Maia's concrete signal type here.
public struct ProprietarySignalRef: Sendable, Hashable {
    public let id: UInt16
    public init(id: UInt16) { self.id = id }
}

/// Where we can get between the car and itself. Different points give
/// genuinely different outcomes, which is why the action list depends on them.
public enum InterceptionPoint: String, Sendable, Codable, Hashable, CaseIterable {
    /// A discrete wire feeding the module — one relay per signal.
    case inputDiscrete
    /// A CAN-carried signal, rewritten in transit by a transparent gateway.
    case inputCAN
    /// The module's speaker feed.
    case output

    public var displayName: String {
        switch self {
        case .inputDiscrete: return "Input (wire)"
        case .inputCAN: return "Input (CAN gateway)"
        case .output: return "Speaker tap"
        }
    }

    public var isInput: Bool { self != .output }
}

/// What we do when a chime fires.
public enum ChimeAction: String, Sendable, Codable, CaseIterable {
    /// Leave the car alone. The honest default until hardware exists.
    case passthrough
    /// Rewrite the input so the module never decides to warn at all —
    /// no chime *and* no telltale. Needs an input interception point.
    case prevent
    /// Attenuate the factory tone. Output side; the telltale still lights.
    case quieter
    /// Suppress the sound. Output side; the telltale still lights.
    case muted
    /// Suppress it and play our own sound instead. Output side.
    case replaced

    public var displayName: String {
        switch self {
        case .passthrough: return "Pass through"
        case .prevent: return "Prevent"
        case .quieter: return "Quieter"
        case .muted: return "Muted"
        case .replaced: return "Replace"
        }
    }

    /// The distinction that matters in practice.
    public var effect: String {
        switch self {
        case .passthrough: return "Stock behavior."
        case .prevent: return "The module never decides to warn — no sound and no dash light."
        case .quieter: return "Factory tone, attenuated. Dash light still shows."
        case .muted: return "Silent, but the dash light still shows."
        case .replaced: return "Factory tone silenced, your sound plays instead. Dash light still shows."
        }
    }

    public var requiredPoints: Set<InterceptionPoint> {
        switch self {
        case .passthrough: return []
        case .prevent: return [.inputDiscrete, .inputCAN]  // either will do
        case .quieter, .muted, .replaced: return [.output]
        }
    }
}

public struct ChimePolicy: Sendable, Codable, Equatable, Identifiable {
    public var id: String          // matches Chime.id
    public var action: ChimeAction
    /// Used when action == .replaced.
    public var sound: AlertSound
    public var volume: Double

    public init(id: String, action: ChimeAction = .passthrough,
                sound: AlertSound = .silent, volume: Double = 1.0) {
        self.id = id
        self.action = action
        self.sound = sound
        self.volume = volume
    }
}

public extension Chime {
    /// The 2022 Forester's chimes, from docs/design/chimes.md.
    static let foresterChimes: [Chime] = [
        Chime(id: "gate", name: "Rear gate ajar",
              detail: "The one that started this project. Fires continuously while driving with the gate open.",
              reach: .clusterTap, points: [.inputCAN, .output],
              signal: ProprietarySignalRef(id: ProprietarySignal.gate.id)),
        Chime(id: "seatbelt", name: "Seatbelt reminder",
              detail: "Escalates with speed and time. No factory setting exists for it.",
              reach: .clusterTap, points: [.inputDiscrete, .inputCAN, .output],
              signal: ProprietarySignalRef(id: ProprietarySignal.beltDriver.id)),
        Chime(id: "door", name: "Door ajar",
              detail: "Door open with the ignition on.",
              reach: .clusterTap, points: [.inputCAN, .output],
              signal: ProprietarySignalRef(id: ProprietarySignal.doorFrontLeft.id)),
        Chime(id: "turnsignal", name: "Turn signal tick",
              detail: "Synthesized by the cluster from the stalk switch — no input we can reach.",
              reach: .clusterTap, points: [.output]),
        Chime(id: "eyesight", name: "EyeSight / pre-collision",
              detail: "Routed through the head unit and the cluster on the 2022.",
              reach: .headUnit, points: [.output]),
        Chime(id: "reverse", name: "Reverse / park sensors",
              detail: "Body unit through the rear speaker.",
              reach: .headUnit, points: [.output]),
        Chime(id: "keyless", name: "Keyless entry beep",
              detail: "Separate buzzer. Seven volume levels including off, via dealer settings.",
              reach: .bodySetting, points: [.output]),
    ]
}

/// JSON-file-backed chime policies, one per chime, plus which interception
/// hardware is actually installed. A policy can be *set* before the hardware
/// exists; whether it's *enforced* is a separate fact and the UI says so.
public actor ChimePolicyStore {
    private let fileURL: URL
    private let hardwareURL: URL
    private var policies: [String: ChimePolicy]
    private var installed: Set<InterceptionPoint>

    public init(directory: URL? = nil) {
        let base = directory ?? FileManager.default
            .urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
            .appendingPathComponent("pleiades", isDirectory: true)
        try? FileManager.default.createDirectory(at: base, withIntermediateDirectories: true)
        fileURL = base.appendingPathComponent("chime-policies.json")
        hardwareURL = base.appendingPathComponent("chime-hardware.json")
        if let data = try? Data(contentsOf: fileURL),
           let loaded = try? JSONDecoder().decode([String: ChimePolicy].self, from: data) {
            policies = loaded
        } else {
            policies = [:]
        }
        if let data = try? Data(contentsOf: hardwareURL),
           let loaded = try? JSONDecoder().decode(Set<InterceptionPoint>.self, from: data) {
            installed = loaded
        } else {
            installed = []
        }
    }

    public func installedPoints() -> Set<InterceptionPoint> { installed }

    public func setInstalled(_ points: Set<InterceptionPoint>) {
        installed = points
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        try? encoder.encode(installed).write(to: hardwareURL, options: .atomic)
    }

    /// Every chime, with its stored policy or a passthrough default.
    public func all() -> [ChimePolicy] {
        Chime.foresterChimes.map { policies[$0.id] ?? ChimePolicy(id: $0.id) }
    }

    public func policy(for id: String) -> ChimePolicy {
        policies[id] ?? ChimePolicy(id: id)
    }

    public func save(_ policy: ChimePolicy) {
        policies[policy.id] = policy
        persist()
    }

    public func resetAll() {
        policies = [:]
        persist()
    }

    private func persist() {
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        try? encoder.encode(policies).write(to: fileURL, options: .atomic)
    }
}
