import Foundation
import Maia

/// Renders the bundled platform registries into `docs/SIGNALS.md`.
///
/// Uses `VehicleRegistry` rather than re-parsing the JSON, so confidence is
/// derived in exactly one place. The markdown is never hand-edited — it's the
/// data, rendered — and `bench.sh` fails if the two disagree.
///
/// What's *not* known is tracked as carefully as what is. An identifier that
/// answers with no known meaning is a work item, not an absence.
enum Registry {
    static let directory = "Sources/Maia/Resources/registry"
    static let markdownPath = "docs/SIGNALS.md"

    static func run(check: Bool) throws {
        let registries = try load()
        guard !registries.isEmpty else { throw RegistryError.malformed("no registries in \(directory)") }
        let rendered = registries.map { render($0.registry, raw: $0.raw) }.joined(separator: "\n\n")

        if check {
            let existing = (try? String(contentsOfFile: markdownPath, encoding: .utf8)) ?? ""
            guard existing == rendered else {
                print("✗ \(markdownPath) is stale — run `pleiades registry` to regenerate")
                exit(1)
            }
            print("✓ \(markdownPath) matches \(directory)")
            return
        }

        try rendered.write(toFile: markdownPath, atomically: true, encoding: .utf8)
        print("Wrote \(markdownPath)")
        for entry in registries { summarise(entry.registry) }
    }

    private static func load() throws -> [(registry: VehicleRegistry, raw: [String: Any])] {
        let names = try FileManager.default.contentsOfDirectory(atPath: directory)
            .filter { $0.hasSuffix(".json") }
            .sorted()
        return try names.map { name in
            let data = try Data(contentsOf: URL(fileURLWithPath: "\(directory)/\(name)"))
            let raw = (try JSONSerialization.jsonObject(with: data) as? [String: Any]) ?? [:]
            return (try VehicleRegistry(data: data), raw)
        }
    }

    // MARK: - Rendering

    private static func render(_ r: VehicleRegistry, raw: [String: Any]) -> String {
        var out: [String] = []
        out.append("""
        <!-- Generated by `pleiades registry` from Sources/Maia/Resources/registry/. Do not edit by hand. -->

        # \(r.platform.name)

        What this platform's modules will tell you, and **how anybody knows**.
        Confidence is derived from evidence, never asserted — see
        `docs/registry-format.md`. A row saying *confirmed* means somebody
        watched it change and change back, or two people on different cars
        reached the same answer.

        **Models:** \(r.platform.models.joined(separator: ", "))
        **Protocol:** \(r.platform.protocolDescription)
        **Contributors:** \(r.contributors.map(\.id).joined(separator: ", "))

        \(r.modules.count) modules · **\(r.count(.confirmed)) confirmed** · \
        \(r.count(.candidate)) candidate · \(r.unknownCount) answering with no known meaning
        """)

        out.append("\n## Confidence\n")
        out.append("| Label | Meaning |\n|---|---|")
        for confidence in VehicleRegistry.Confidence.allCases {
            out.append("| `\(confidence.rawValue)` | \(confidence.detail) |")
        }

        out.append("\n## Modules\n")
        out.append("| Address | Name | Role | Pages | Identifiers |\n|---|---|---|---|---|")
        for module in r.modules {
            let known = module.count(.confirmed) + module.count(.candidate)
            let summary = module.identifiersAnswering > 0
                ? "\(known) named / \(module.identifiersAnswering) answer"
                : (known > 0 ? "\(known) named" : "—")
            let pages = module.pages.joined(separator: " ")
            out.append("| `\(module.label)` | \(module.name) | \(module.role ?? "") | \(pages.isEmpty ? "—" : "`\(pages)`") | \(summary) |")
        }

        for module in r.modules where !module.signals.isEmpty || module.todo != nil {
            out.append("\n### `\(module.label)` — \(module.name)\n")
            if let todo = module.todo { out.append("> **Not yet explored.** \(todo)\n") }
            guard !module.signals.isEmpty else { continue }
            out.append("| Identifier | Signal | Confidence | Encoding | How we know |\n|---|---|---|---|---|")
            for signal in module.signals {
                var how = signal.method ?? "—"
                if let evidence = signal.evidence { how += " (`\(evidence)`)" }
                if let first = signal.firstObservation {
                    how += " — \(first.by), \(first.date)"
                    if !first.discriminated.isEmpty {
                        how += "; ruled out \(first.discriminated.joined(separator: ", "))"
                    }
                }
                out.append("| `\(signal.command)` | \(signal.name) | `\(signal.confidence.rawValue)` | \(describe(signal.encoding)) | \(how) |")
            }
        }

        if !r.openQuestions.isEmpty {
            out.append("\n## What we don't know yet\n")
            out.append("The work queue. Each is answerable with the tools already built.\n")
            for question in r.openQuestions {
                out.append("**\(question.question)**\n")
                if let why = question.whyItMatters { out.append("- *Why it matters:* \(why)") }
                if let how = question.howToAnswer { out.append("- *How to answer:* \(how)") }
                out.append("")
            }
        }

        out.append(narrative(raw, key: "buses", title: "Buses", name: "name", detail: "access"))
        out.append(narrative(raw, key: "conventions", title: "Conventions this car follows", name: "name", detail: "detail"))
        out.append(narrative(raw, key: "sources", title: "Sources", name: "name", detail: "note"))
        return out.joined(separator: "\n") + "\n"
    }

    private static func describe(_ encoding: VehicleRegistry.Encoding) -> String {
        switch encoding {
        case .boolean(let on, let off):
            return String(format: "boolean, true=`%02X`%@", on, off.map { String(format: ", false=`%02X`", $0) } ?? "")
        case .scaled(let divisor, let unit, let bytes):
            return "uint\(bytes * 8) ÷ \(Int(divisor))\(unit.isEmpty ? "" : " \(unit)")"
        case .enumerated(let values):
            return "enum (\(values.count) values)"
        case .raw:
            return "raw"
        }
    }

    /// The prose sections the typed model doesn't carry — narrative about the
    /// car rather than facts about identifiers.
    private static func narrative(
        _ raw: [String: Any], key: String, title: String, name: String, detail: String
    ) -> String {
        guard let entries = raw[key] as? [[String: Any]], !entries.isEmpty else { return "" }
        var out = ["\n## \(title)\n"]
        for entry in entries {
            out.append("**\((entry[name] as? String) ?? "?")**\n")
            for field in [detail, "note", "consequence", "evidence", "url"] where field != name {
                if let value = entry[field] as? String {
                    out.append("\(field == "consequence" ? "> " : "")\(value)\n")
                }
            }
        }
        return out.joined(separator: "\n")
    }

    private static func summarise(_ r: VehicleRegistry) {
        print("""

          \(r.platform.name)
          \(r.modules.count) modules · \(r.count(.confirmed)) confirmed · \
        \(r.count(.candidate)) candidate · \(r.count(.rejected)) rejected
          \(r.totalAnswering) identifiers answer; \(r.unknownCount) have no known meaning
          \(r.openQuestions.count) open questions · fingerprint of \(r.platform.fingerprint.count) modules
        """)
    }
}

enum RegistryError: Error, CustomStringConvertible {
    case malformed(String)
    var description: String {
        switch self {
        case .malformed(let why): "registry is malformed: \(why)"
        }
    }
}
